Test update deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -83,7 +83,7 @@ jobs:
         run: |
           echo "Applying Kubernetes deployment..."
           export KUBECONFIG="$HOME/k3s.yaml"
-          kubectl apply -f docker/deploy.yml || echo "Failed to apply Kubernetes deployment"
+#          kubectl apply -f docker/deploy.yml || echo "Failed to apply Kubernetes deployment"
           
           # Debugging: Verify the applied resources
           kubectl get deployments || echo "Failed to get deployments"
